sudo: false

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack/

matrix:
  include:
  - env: RESOLVER="lts-11.10"

before_install:
  # Download pre-built mxnet library.
  - wget -O mxnet-lib.tar.gz "https://drive.google.com/uc?export=download&id=1yY_zIiGm12wdsWeuwLaQuEwnfc2QKc8i" # version 1.0
  - tar zxf mxnet-lib.tar.gz
  - |
    printf "\
    FROM ubuntu:16.04
    RUN apt-get update && apt-get install -y tar gzip libopencv-dev libopenblas-dev gcc-5 g++-5 libc6 libgmp-dev
    RUN curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C /usr/bin '*/stack' && chmod +x /usr/bin/stack
    ADD mxnet-lib /mxnet-lib
    ENV LD_LIBRARY_PATH=/mxnet-lib/lib
    WORKDIR /code
    " > Dockerfile
  - cat Dockerfile

install:
  - docker build -t buildenv .

script:
  - echo $TRAVIS_BUILD_DIR
  - > 
    docker run -v $HOME/.stack:/root/.stack \
               -v $HOME/.ghc:/root/.ghc \
               -v $TRAVIS_BUILD_DIR:/code \
               buildenv \
               stack --allow-different-user --resolver $RESOLVER build \
                     --extra-include-dirs=/mxnet-lib/include \
                     --extra-include-dirs=/mxnet-lib/nnvm/include \
                     --extra-lib-dirs=/mxnet-lib/lib \
                     --extra-lib-dirs=/mxnet-lib/nnvm/lib \
                     --haddock --no-haddock-deps
