sudo: required
language: haskell

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack/

# dependent apt packages.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - unzip
    - gcc-4.8
    - g++-4.8
    - libatlas-dev
    - libatlas-base-dev
    - libopencv-dev

matrix:
  include:
  - env: BUILD=stack RESOLVER="lts-7.9"
    compiler: "#stack ghc-8.0.1"
  - env: BUILD=stack RESOLVER="lts-8.0"
    compiler: "#stack ghc-8.0.2"
  - env: BUILD=stack RESOLVER="nightly-2017-10-11"
    compiler: "#stack ghc-8.2.1"
  allow_failures:
  - env: BUILD=stack RESOLVER="lts-7.9"
    compiler: "#stack ghc-8.0.1"
  - env: BUILD=stack RESOLVER="lts-8.0"
    compiler: "#stack ghc-8.0.2"

before_install:
  # Set up the correct version of gcc and g++.
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  # Download pre-built mxnet library.
  - wget -O mxnet-lib.zip "https://drive.google.com/uc?export=download&id=0B3nF_Z9CRFTUZlhyQXFubUF5OUU" # version 0.12.0-rc0
  - unzip mxnet-lib.zip -O mxnet-lib
  - export LIBRARY_PATH=~/mxnet-lib/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=~/mxnet-lib/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=~/mxnet-lib/include:$C_INCLUDE_PATH
  # Set up haskell environment.
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod +x ~/.local/bin/stack

install:
  - stack setup --resolver $RESOLVER

script:
  - cd $TRAVIS_BUILD_DIR
  - stack --resolver $RESOLVER build --bench --test --coverage --haddock --no-haddock-deps
