sudo: required
language: haskell

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work/

# dependent apt packages.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - git
    - gcc-4.8
    - g++-4.8
    - libatlas-dev
    - libatlas-base-dev
    - libopencv-dev

matrix:
  include:
  - env: BUILD=stack RESOLVER="lts-6.25"
    compiler: "#stack GHC-7.10.3"
  - env: BUILD=stack RESOLVER="lts-7.9"
    compiler: "#stack GHC-8.0.1"

before_install:
  # Set up the correct version of gcc and g++.
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  # Build mxnet library.
  - git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive
  - cd ~/mxnet && git checkout v0.9.3 && make && cd ~
  - mkdir -p ~/.local/lib
  - cp -f ~/mxnet/lib/libmxnet.so ~/.local/lib/
  - export LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=~/mxnet/include:~/mxnet/nnvm/include:~/mxnet/dmlc-core/include:$C_INCLUDE_PATH
  # Set up haskell environment.
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod +x ~/.local/bin/stack

install:
  - stack setup --resolver $RESOLVER

script:
  - cd $TRAVIS_BUILD_DIR
  - stack --resolver $RESOLVER build --bench --test --coverage --haddock --no-haddock-deps
