sudo: false
dist: trusty
services:
  - docker

matrix:
  include:
  - env: RESOLVER="lts-11.10"

before_install:
  # Download pre-built mxnet library.
  - wget -O mxnet-lib.tar.gz "https://drive.google.com/uc?export=download&id=1yY_zIiGm12wdsWeuwLaQuEwnfc2QKc8i" # version 1.0
  - tar zxf mxnet-lib.tar.gz
  - sudo cp mxnet-lib/lib/libmxnet.so /usr/lib/
  - sudo cp -R mxnet-lib/include/mxnet /usr/include/
  - sudo cp -R mxnet-lib/nnvm/include/nnvm /usr/include/
  - |
cat << EOF > Dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y tar gzip libopencv-dev libopenblas-dev gcc-5 g++-5 libc6
RUN curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C /usr/bin '*/stack' && chmod +x /usr/bin/stack
stack setup --resolver $RESOLVER

EOF
  - cat Dockerfile

install:
  - docker build -t buildenv .

script:
  - docker run -v /code:$TRAVIS_BUILD_DIR stack --resolver $RESOLVER build --haddock --no-haddock-deps
