sudo: required
language: haskell

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack/

# dependent apt packages.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tar
    - gzip

matrix:
  include:
  - env: BUILD=stack RESOLVER="lts-11.10"
    compiler: "#stack ghc-8.2.2"

before_install:
  # Download pre-built mxnet library.
  - wget -O mxnet-lib.tar.gz "https://drive.google.com/uc?export=download&id=1yY_zIiGm12wdsWeuwLaQuEwnfc2QKc8i" # version 1.0
  - tar zxf mxnet-lib.tar.gz
  - cp mxnet-lib/lib/libmxnet.so /usr/lib/
  - cp -R mxnet-lib/include/nnvm /usr/include/
  - cp -R mxnet-lib/include/mxnet /usr/include/
  # Set up haskell environment.
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod +x ~/.local/bin/stack

install:
  - stack setup --resolver $RESOLVER

script:
  - cd $TRAVIS_BUILD_DIR
  - stack --resolver $RESOLVER build --haddock --no-haddock-deps
  - stack --resolver $RESOLVER test mxnet
