resolver: lts-9.14

packages:
- c2hs-extra
- mxnet
- mxnet-examples

extra-deps:
- tuple-ops-0.0.0.1

flags: {}

extra-package-dbs: []

extra-include-dirs:
- /home/jason/incubator-mxnet/include
- /home/jason/incubator-mxnet/nnvm/include
extra-lib-dirs:
- /home/jason/incubator-mxnet/lib
- /home/jason/incubator-mxnet/nnvm/lib